const users = [
  {
    email: "user1@example.com",
    name: "John",
    last_name: "Doe",
    phone_number: "1234567890",
    birthdate: "1990-01-01",
    username: "user1",
    password: "myPassword123",
  },
  {
    email: "user2@example.com",
    name: "Jane",
    last_name: "Smith",
    phone_number: "9876543210",
    birthdate: "1995-02-15",
    username: "user2",
    password: "myPassword456",
  },
  {
    email: "user3@example.com",
    name: "David",
    last_name: "Johnson",
    phone_number: "5555555555",
    birthdate: "1988-07-10",
    username: "user3",
    password: "myPassword789",
  },
  {
    email: "user4@example.com",
    name: "Emily",
    last_name: "Brown",
    phone_number: "9999999999",
    birthdate: "1992-04-22",
    username: "user4",
    password: "myPasswordabc",
  },
  {
    email: "user5@example.com",
    name: "Michael",
    last_name: "Wilson",
    phone_number: "1111111111",
    birthdate: "1985-12-05",
    username: "user5",
    password: "myPasswordxyz",
  },
  {
    email: "user6@example.com",
    name: "Emma",
    last_name: "Davis",
    phone_number: "2222222222",
    birthdate: "1993-09-18",
    username: "user6",
    password: "myPassword123",
  },
  {
    email: "user7@example.com",
    name: "Daniel",
    last_name: "Taylor",
    phone_number: "3333333333",
    birthdate: "1991-03-25",
    username: "user7",
    password: "myPassword456",
  },
  {
    email: "user8@example.com",
    name: "Olivia",
    last_name: "Anderson",
    phone_number: "4444444444",
    birthdate: "1994-08-14",
    username: "user8",
    password: "myPassword789",
  },
  {
    email: "user9@example.com",
    name: "William",
    last_name: "Lee",
    phone_number: "7777777777",
    birthdate: "1987-06-30",
    username: "user9",
    password: "myPasswordabc",
  },
  {
    email: "user10@example.com",
    name: "Sophia",
    last_name: "Clark",
    phone_number: "8888888888",
    birthdate: "1996-11-12",
    username: "user10",
    password: "myPasswordxyz",
  },
];
const currencies = [
  {
    currency_id: 1,
    currency_code: "USD",
    currency_name: "United States Dollar",
    currency_symbol: "$",
  },
  {
    currency_id: 2,
    currency_code: "EUR",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    currency_id: 3,
    currency_code: "GBP",
    currency_name: "British Pound Sterling",
    currency_symbol: "£",
  },
  {
    currency_id: 4,
    currency_code: "JPY",
    currency_name: "Japanese Yen",
    currency_symbol: "¥",
  },
  {
    currency_id: 5,
    currency_code: "CAD",
    currency_name: "Canadian Dollar",
    currency_symbol: "CA$",
  },
  {
    currency_id: 6,
    currency_code: "AUD",
    currency_name: "Australian Dollar",
    currency_symbol: "A$",
  },
  {
    currency_id: 7,
    currency_code: "CHF",
    currency_name: "Swiss Franc",
    currency_symbol: "CHF",
  },
  {
    currency_id: 8,
    currency_code: "NZD",
    currency_name: "New Zealand Dollar",
    currency_symbol: "NZ$",
  },
  {
    currency_id: 9,
    currency_code: "ILS",
    currency_name: "Israeli Shekel",
    currency_symbol: "₪",
  },
  {
    currency_id: 10,
    currency_code: "SEK",
    currency_name: "Swedish Krona",
    currency_symbol: "kr",
  },
];
const transactions = [
  {
    date: "2023-06-01",
    city: "Tel Aviv",
    address: "123 Main Street",
    from_currency_id: 1,
    to_currency_id: 2,
    amount: 100.5,
    status: "Pending",
    from_user_id: 1,
    to_user_id: null,
  },
  {
    date: "2023-06-02",
    city: "Jerusalem",
    address: "456 Oak Avenue",
    from_currency_id: 2,
    to_currency_id: 3,
    amount: 250.75,
    status: "Pending",
    from_user_id: 3,
    to_user_id: null,
  },
  {
    date: "2023-06-03",
    city: "Tel Aviv",
    address: "789 Elm Road",
    from_currency_id: 3,
    to_currency_id: 1,
    amount: 50.25,
    status: "Pending",
    from_user_id: 2,
    to_user_id: null,
  },
  {
    date: "2023-06-04",
    city: "Haifa",
    address: "321 Cedar Lane",
    from_currency_id: 1,
    to_currency_id: 3,
    amount: 75.0,
    status: "Pending",
    from_user_id: 1,
    to_user_id: null,
  },
  {
    date: "2023-06-05",
    city: "Tel Aviv",
    address: "567 Pine Street",
    from_currency_id: 2,
    to_currency_id: 1,
    amount: 150.0,
    status: "Pending",
    from_user_id: 3,
    to_user_id: null,
  },
  {
    date: "2023-06-06",
    city: "Jerusalem",
    address: "987 Maple Avenue",
    from_currency_id: 3,
    to_currency_id: 2,
    amount: 200.5,
    status: "Pending",
    from_user_id: 2,
    to_user_id: null,
  },
  {
    date: "2023-06-07",
    city: "Tel Aviv",
    address: "654 Oak Road",
    from_currency_id: 1,
    to_currency_id: 2,
    amount: 300.75,
    status: "Pending",
    from_user_id: 1,
    to_user_id: null,
  },
  {
    date: "2023-06-08",
    city: "Haifa",
    address: "789 Elm Street",
    from_currency_id: 2,
    to_currency_id: 3,
    amount: 175.25,
    status: "Pending",
    from_user_id: 3,
    to_user_id: null,
  },
];
module.exports = { users, currencies, transactions };
